// Sweeper – Sync Focuses to 3lm.js
// Syncs focus definitions from Focuses.md into 3lm semantic memory.
// Ensures AI knows your focus areas at session start.
// Focuses.md is canonical. This script bridges it to the memory layer.

const { execSync } = require("child_process");
const path = require("path");

module.exports = async (quickAdd) => {
  const { app } = quickAdd;
  const vault = app.vault;

  const focusesPath = "AI-Suplex-777/Focuses.md";
  if (!(await vault.adapter.exists(focusesPath))) {
    new Notice("Focuses.md not found. Run Focus Manager first.");
    return;
  }

  const content = await vault.adapter.read(focusesPath);
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) {
    new Notice("Invalid Focuses.md frontmatter.");
    return;
  }

  const frontmatter = match[1];
  const nameMatches = [...frontmatter.matchAll(/name:\s*(\S+)/g)];
  const focusNames = nameMatches.map((m) => m[1]);

  if (focusNames.length === 0) {
    new Notice("No focuses found in Focuses.md.");
    return;
  }

  // Build semantic memory content
  let semanticContent = `# Focus Areas\n\n`;
  semanticContent += `> Auto-generated by Sync Focuses to 3lm. Do not edit manually.\n`;
  semanticContent += `> Source: Focuses.md (canonical)\n\n`;

  let synced = 0;
  for (const focus of focusNames) {
    const mocPath = `AI-Suplex-777/MOCs/${focus} MOC.md`;
    let summary = "No MOC found.";

    if (await vault.adapter.exists(mocPath)) {
      const mocContent = await vault.adapter.read(mocPath);
      // Extract first 500 chars of content (after frontmatter)
      const mocBody = mocContent.replace(/^---[\s\S]*?---\n/, "").trim();
      summary = mocBody.slice(0, 500).replace(/\n/g, " ").replace(/"/g, "'");
      if (summary.length === 500) summary += "...";
    }

    semanticContent += `## ${focus}\n`;
    semanticContent += `- MOC: [[${focus} MOC]]\n`;
    semanticContent += `- Summary: ${summary}\n\n`;
    synced++;
  }

  // Write to Memory/semantic/focuses.md
  const semanticPath = "AI-Suplex-777/Memory/semantic/focuses.md";
  if (await vault.adapter.exists(semanticPath)) {
    await vault.modify(vault.getAbstractFileByPath(semanticPath), semanticContent);
  } else {
    await vault.create(semanticPath, semanticContent);
  }

  new Notice(`✅ Synced ${synced} focuses to 3lm memory`, 3000);

  // Run 3lm index to refresh lookup
  try {
    const vaultPath = app.vault.adapter.basePath;
    const cwd = vaultPath + "/AI-Suplex-777";
    execSync("node Tools/3lm.js index", {
      encoding: "utf8",
      timeout: 15000,
      stdio: "pipe",
      cwd,
    });
    new Notice("✅ Memory index refreshed", 2000);
  } catch (e) {
    console.error("3lm index error: " + e.message);
  }
};
