// Sweeper – Refresh B-Bomb Index.js
// Scans all B-Bombs, writes summaries to 3lm semantic memory,
// and refreshes the memory index.
// B-Bombs are the most valuable artifacts — the AI should know them all.

const { execSync } = require("child_process");
const path = require("path");

module.exports = async (quickAdd) => {
  const { app } = quickAdd;
  const vault = app.vault;

  const bBombFolder = "AI-Suplex-777/B-Bombs";
  if (!(await vault.adapter.exists(bBombFolder))) {
    new Notice("B-Bombs folder not found.");
    return;
  }

  const files = vault
    .getFiles()
    .filter((f) => f.path.startsWith(bBombFolder) && f.extension === "md");

  if (files.length === 0) {
    new Notice("No B-Bombs found.");
    return;
  }

  // Build semantic memory content
  let semanticContent = `# B-Bomb Index\n\n`;
  semanticContent += `> Auto-generated by Refresh B-Bomb Index. Do not edit manually.\n`;
  semanticContent += `> Source: B-Bombs/ folder (canonical)\n`;
  semanticContent += `> Total: ${files.length} B-Bombs\n\n`;

  let indexed = 0;
  for (const file of files) {
    try {
      const content = await vault.read(file);
      const frontmatter =
        app.metadataCache.getCache(file.path)?.frontmatter || {};
      const focus = frontmatter.focus || "general";
      const tags = (frontmatter.tags || []).join(", ");
      const title = frontmatter.title || file.basename;
      const date = frontmatter.date || "unknown";

      // Extract summary — prefer ## Description section, fallback to first 300 chars
      const body = content.replace(/^---[\s\S]*?---\n/, "").trim();
      let summary = "";
      const descMatch = body.match(/## Description\n([\s\S]*?)(?=\n## |$)/);
      if (descMatch) {
        summary = descMatch[1].trim().slice(0, 300).replace(/\n/g, " ").replace(/"/g, "'");
      } else {
        summary = body.slice(0, 300).replace(/\n/g, " ").replace(/"/g, "'");
      }
      if (summary.length === 300) summary += "...";

      semanticContent += `## ${title}\n`;
      semanticContent += `- File: [[${file.basename.replace(".md", "")}]]\n`;
      semanticContent += `- Focus: ${focus}\n`;
      semanticContent += `- Date: ${date}\n`;
      semanticContent += `- Tags: ${tags}\n`;
      semanticContent += `- Summary: ${summary}\n\n`;
      indexed++;
    } catch (e) {
      console.error(`Failed to index ${file.path}: ${e.message}`);
    }
  }

  // Write to Memory/semantic/b-bombs.md
  const semanticPath = "AI-Suplex-777/Memory/semantic/b-bombs.md";
  if (await vault.adapter.exists(semanticPath)) {
    await vault.modify(vault.getAbstractFileByPath(semanticPath), semanticContent);
  } else {
    await vault.create(semanticPath, semanticContent);
  }

  new Notice(`✅ Indexed ${indexed} B-Bombs to 3lm memory`, 3000);

  // Run 3lm index to refresh lookup
  try {
    const vaultPath = app.vault.adapter.basePath;
    const cwd = vaultPath + "/AI-Suplex-777";
    execSync("node Tools/3lm.js index", {
      encoding: "utf8",
      timeout: 15000,
      stdio: "pipe",
      cwd,
    });
    new Notice("✅ Memory index refreshed", 2000);
  } catch (e) {
    console.error("3lm index error: " + e.message);
  }
};
