// Sweeper – Generate Cycle Review.js
// Generates a cycle review by aggregating episodes from the cycle.
// Reads Memory/episodic/Cycle-X/ and creates a review summary.

const { execSync } = require("child_process");
const path = require("path");

module.exports = async (quickAdd) => {
  const { app } = quickAdd;
  const vault = app.vault;

  // Determine current cycle from date
  const now = new Date();
  const month = now.getMonth() + 1;
  const cycle = Math.ceil(month / 2) || 1;
  const cycleDir = `Cycle-${cycle}`;

  const episodicPath = `AI-Suplex-777/Memory/episodic/${cycleDir}`;
  if (!(await vault.adapter.exists(episodicPath))) {
    new Notice(`No episodes found for ${cycleDir}.`);
    return;
  }

  // Scan for all .md files in the cycle's episodic memory
  const files = vault
    .getFiles()
    .filter((f) => f.path.startsWith(episodicPath) && f.extension === "md");

  if (files.length === 0) {
    new Notice(`No episodes found for ${cycleDir}.`);
    return;
  }

  // Build review content
  let reviewContent = `# Cycle ${cycle} Review\n\n`;
  reviewContent += `**Generated:** ${now.toISOString().split("T")[0]}\n`;
  reviewContent += `**Episodes:** ${files.length}\n\n`;
  reviewContent += `---\n\n`;

  let totalInsights = 0;
  for (const file of files) {
    try {
      const content = await vault.read(file);
      const frontmatter =
        app.metadataCache.getCache(file.path)?.frontmatter || {};
      const sessionId = frontmatter.session_id || file.basename;
      const focus = frontmatter.focus || "general";

      // Extract insights section
      const insightsMatch = content.match(/## Insights\n([\s\S]*?)(?=\n## |$)/);
      const insights = insightsMatch ? insightsMatch[1].trim() : "No insights captured.";

      reviewContent += `### ${sessionId}\n`;
      reviewContent += `- Focus: ${focus}\n`;
      reviewContent += `- Insights: ${insights.slice(0, 200)}\n\n`;
      totalInsights++;
    } catch (e) {
      console.error(`Failed to read ${file.path}: ${e.message}`);
    }
  }

  reviewContent += `---\n\n`;
  reviewContent += `**Total episodes reviewed:** ${totalInsights}\n`;
  reviewContent += `**Generated by:** Sweeper – Generate Cycle Review\n`;

  // Save to Reviews/Weekly/Cycle-X/
  const reviewPath = `AI-Suplex-777/Reviews/Weekly/${cycleDir}`;
  if (!(await vault.adapter.exists(reviewPath))) {
    await vault.createFolder(reviewPath);
  }

  const fileName = `Cycle ${cycle} Review.md`;
  const filePath = `${reviewPath}/${fileName}`;

  if (await vault.adapter.exists(filePath)) {
    const existing = await vault.adapter.read(filePath);
    await vault.modify(vault.getAbstractFileByPath(filePath), reviewContent);
  } else {
    await vault.create(filePath, reviewContent);
  }

  new Notice(`✅ Cycle ${cycle} review generated (${totalInsights} episodes)`, 3000);

  // Run 3lm promote to score lessons
  try {
    const vaultPath = app.vault.adapter.basePath;
    const cwd = vaultPath + "/AI-Suplex-777";
    execSync("node Tools/3lm.js promote --min 70", {
      encoding: "utf8",
      timeout: 15000,
      stdio: "pipe",
      cwd,
    });
    new Notice("✅ 3lm promote completed", 2000);
  } catch (e) {
    console.error("3lm promote error: " + e.message);
  }
};
